---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: superbasic
spec:
  basicAuth:
    secret: htpasswd

---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata: 
  name: heimdall
spec:
  forwardAuth: 
    address: "https://heimdall.heimdall.svc.cluster.local:4456" 
    authResponseHeaders: 
      - Authorization

---
apiVersion: traefik.io/v1alpha1
kind: ServersTransport
metadata:
  name: insecure-transport
spec:
  insecureSkipVerify: true
